language: go
go:
- 1.6
- 1.7
- tip
notifications:
  slack:
    secure: Az/L2UjJj6ogWQAgRMjsFEVpqLPoOCazIZ9fMhq5hQmQUnbzbxW4dZVxE3WN+3b2NBZb+Eisd2mxFRetBXwCmDH+R0g0LjL3HM6i9rXMsn2lzuXIeRXARL+hoC++9XqHjCk2D2zDqpExXIL9ICDhllKJKsihntYYJFIhhJTdELBGiVgVw6ByXNyHsnR1c0FV8cv3xyBjT34rQcBfuCZbv5KdI9BMM1v/ZpfUPmn9FThz/5K/kQKfpQJTbpgJZ3bwcUr3yQG0ZfDJg8ka9Fha73NvZoWyaMSb/aZXJVDGOAdHKRXL4Jf+EnUKc4NWzF8tldy7hRQUzpxotqUgaPVdMKy0eUwBMXsBrQ3Xm0k9YA1mOtL/L+vbhWNr5WOpLOoN5dmXf4JBG0eTZYLjQ++i1v8HI1b6t5PSRVDkPCe1MwLWQJia577NsO6PPcFx5PmBzkLOtDMN54CpIsUVabBLag2g/ZHNQNON70FHOarkzi+xb+LdIJQ4fUiccJ6UbXU/tSLc7aDepZGl/Mw/F61hXmT2dl+KOG4JYTgKmVKfIF0he2Q4bugTV3d69aI9rQmaXFhmArdFdhwNwiID+BqKfRdnE0x7wuyHxQX20zTdqGndF+pgw0OXiEt9cWR16lG7Ws9IJpikJzBgSG/w9EsKMCKl1TaNMlJGI8ze7w8LBaQ=
