language: go
sudo: false
go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "tip"
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  slack:
    secure: Az/L2UjJj6ogWQAgRMjsFEVpqLPoOCazIZ9fMhq5hQmQUnbzbxW4dZVxE3WN+3b2NBZb+Eisd2mxFRetBXwCmDH+R0g0LjL3HM6i9rXMsn2lzuXIeRXARL+hoC++9XqHjCk2D2zDqpExXIL9ICDhllKJKsihntYYJFIhhJTdELBGiVgVw6ByXNyHsnR1c0FV8cv3xyBjT34rQcBfuCZbv5KdI9BMM1v/ZpfUPmn9FThz/5K/kQKfpQJTbpgJZ3bwcUr3yQG0ZfDJg8ka9Fha73NvZoWyaMSb/aZXJVDGOAdHKRXL4Jf+EnUKc4NWzF8tldy7hRQUzpxotqUgaPVdMKy0eUwBMXsBrQ3Xm0k9YA1mOtL/L+vbhWNr5WOpLOoN5dmXf4JBG0eTZYLjQ++i1v8HI1b6t5PSRVDkPCe1MwLWQJia577NsO6PPcFx5PmBzkLOtDMN54CpIsUVabBLag2g/ZHNQNON70FHOarkzi+xb+LdIJQ4fUiccJ6UbXU/tSLc7aDepZGl/Mw/F61hXmT2dl+KOG4JYTgKmVKfIF0he2Q4bugTV3d69aI9rQmaXFhmArdFdhwNwiID+BqKfRdnE0x7wuyHxQX20zTdqGndF+pgw0OXiEt9cWR16lG7Ws9IJpikJzBgSG/w9EsKMCKl1TaNMlJGI8ze7w8LBaQ=
env:
  global:
    secure: Uk85aOwzdsn7mqcxfcW8K1NMqUzfymn0/J8w9P184oE4aq/SdygSkV5D3hLqbR8wQehY3QJ6zMz8mt+MyLVymOapK+SX+/q2gGXNID6DikcEsMmWDGj+1dBQ+QIzrBTIhVc2KveOf1V1y+9q525ayLyZpgpVNaMV0Djb+6HVTcVz8hNvtJrAQnXkQjERFfh4+odTfFOQBglTOKxwNSxU4CDbrT76TLRJWoTxzWp7q0Km65Pjm7SbR1xm5cVhRwRSE+SClbh1JQqw5HcuomV31ONnbif4JFcXSXPReWyF/RuJLxVIW6NxqQQMIGkJ4qUloCTfyfQUfxPjTpDTivmeToQzsVFM4ojMdTqyZ4d+a4ZcosqmyTDOSm/mAPUVH0v3HIK+giHreGYzbX5XKA28dBEB44k+aDm0icAB3MALWIINNUcRViAXRRV1QNpjHTVNaa3aRpyDEQLIhqzEvGgFgqnm6psJX0yydC1xbHnrfY9ZDLE2wn5i1+4QEk4sNLC9KnFK86dWJK4Qz+ZCneigyOvk9qkcCXBpgtD2Ra7jLfVAV4RNC23WtqqkvFJwQ7uSLk609aMVg0QjYCsUsfyFPXRIbC88V3sZ5qem/fkHQPdY8fnEzXAI5QF89FSgS84vM6DLfzCRhH+6zSWSVKcpU/C7sQblTeyltDtlWjZOozo=
